/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Add: typeof import('./src/components/add.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MultipDeleteTemplate: typeof import('./src/components/MultipDeleteTemplate/index.vue')['default']
    MultiSelect: typeof import('./src/components/multiSelect/index.vue')['default']
    PaginationTemplate: typeof import('./src/components/PaginationTemplate/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar/index.vue')['default']
    SubmitDialog: typeof import('./src/components/SubmitDialog/index.vue')['default']
    TableColumn: typeof import('./src/components/XTable/TableColumn.vue')['default']
    TableDialog: typeof import('./src/components/TableDialog/index.vue')['default']
    TableOperation: typeof import('./src/components/tableOperation/index.vue')['default']
    Upload: typeof import('./src/components/Upload/index.vue')['default']
    XBreadCrumbs: typeof import('./src/components/XBreadCrumbs/index.vue')['default']
    XDialog: typeof import('./src/components/XDialog/index.vue')['default']
    XPagination: typeof import('./src/components/XPagination/index.vue')['default']
    XSureDelete: typeof import('./src/components/XSureDelete/index.vue')['default']
    XTable: typeof import('./src/components/XTable/index.vue')['default']
    XToast: typeof import('./src/components/XToast/index.vue')['default']
  }
}
